language: csharp
solution: GhostBuster.sln
install:
  - nuget restore GhostBuster.sln
  - nuget install NUnit.Runners -Version 3.6.1 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release GhostBuster.sln
  - mono ./testrunner/NUnit.Runners.3.6.1/tools/nunit-console.exe ./GhostBuster.Tests/bin/Release/GhostBuster.Tests.dll


